const ACTION_TYPES = {
  APP_REQUEST: "APP_REQUEST",
  APP_SUCCESS: "APP_SUCCESS",
  APP_FAIL: "APP_FAIL",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  UPLOAD_IMAGE_REQUEST: "UPLOAD_IMAGE_REQUEST",
  UPLOAD_IMAGE_SUCCESS: "UPLOAD_IMAGE_SUCCESS",
  UPLOAD_IMAGE_FAIL: "UPLOAD_IMAGE_FAIL",
};

export default ACTION_TYPES;
