const ACTION_TYPES = {
  CREATE_OR_UPDATE_CART_REQUEST: "CREATE_OR_UPDATE_CART_REQUEST",
  CREATE_OR_UPDATE_CART_SUCCESS: "CREATE_OR_UPDATE_CART_SUCCESS",
  CREATE_OR_UPDATE_CART_FAIL: "CREATE_OR_UPDATE_CART_FAIL",
  GET_CART_INFO_REQUEST: "GET_CART_INFO_REQUEST",
  GET_CART_INFO_SUCCESS: " GET_CART_INFO_SUCCESS",
  GET_CART_INFO_FAIL: " GET_CART_INFO_FAIL",
  UPDATE_QUANTITY_CART_ITEM_REQUEST: "UPDATE_QUANTITY_CART_ITEM_REQUEST",
  UPDATE_QUANTITY_CART_ITEM_SUCCESS: "UPDATE_QUANTITY_CART_ITEM_SUCCESS",
  UPDATE_QUANTITY_CART_ITEM_FAIL: "UPDATE_QUANTITY_CART_ITEM_FAIL",
};

export default ACTION_TYPES;
