const ACTION_TYPES = {
  GET_ALL_CATEGORY_REQUEST: "GET_ALL_CATEGORY_REQUEST",
  GET_ALL_CATEGORY_SUCCESS: "GET_ALL_CATEGORY_SUCCESS",
  GET_ALL_CATEGORY_FAIL: "GET_ALL_CATEGORY_FAIL",
  GET_INFO_CATEGORY_REQUEST: "GET_INFO_CATEGORY_REQUEST",
  GET_INFO_CATEGORY_SUCCESS: "GET_INFO_CATEGORY_SUCCESS",
  GET_INFO_CATEGORY_FAIL: "GET_INFO_CATEGORY_FAIL",
  EDIT_INFO_CATEGORY_REQUEST: "EDIT_INFO_CATEGORY_REQUEST",
  EDIT_INFO_CATEGORY_SUCCESS: "EDIT_INFO_CATEGORY_SUCCESS",
  EDIT_INFO_CATEGORY_FAIL: "EDIT_INFO_CATEGORY_FAIL",
  ADD_CATEGORY_REQUEST: "ADD_CATEGORY_REQUEST",
  ADD_CATEGORY_SUCCESS: "ADD_CATEGORY_SUCCESS",
  ADD_CATEGORY_FAIL: "ADD_CATEGORY_FAIL",
  DELETE_CATEGORY_REQUEST: "DELETE_CATEGORY_REQUEST",
  DELETE_CATEGORY_SUCCESS: "DELETE_CATEGORY_SUCCESS",
  DELETE_CATEGORY_FAIL: "DELETE_CATEGORY_FAIL",
  SET_VISIBLE_CATEGORY_REQUEST: "SET_VISIBLE_CATEGORY_REQUEST",
  SET_VISIBLE_CATEGORY_SUCCESS: "SET_VISIBLE_CATEGORY_SUCCESS",
  SET_VISIBLE_CATEGORY_FAIL: "SET_VISIBLE_CATEGORY_FAIL",
};

export default ACTION_TYPES;
