const ACTION_TYPES = {
  GET_CUSTOMER_INFO_REQUEST: "GET_CUSTOMER_INFO_REQUEST",
  GET_CUSTOMER_INFO_SUCCESS: "GET_CUSTOMER_INFO_SUCCESS",
  GET_CUSTOMER_INFO_FAIL: "GET_CUSTOMER_INFO_FAIL",
};

export default ACTION_TYPES;
