const ACTION_TYPES = {
  GET_ALL_EMPLOYEE_REQUEST: "GET_ALL_EMPLOYEE_REQUEST",
  GET_ALL_EMPLOYEE_SUCCESS: "GET_ALL_EMPLOYEE_SUCCESS",
  GET_ALL_EMPLOYEE_FAIL: "GET_ALL_EMPLOYEE_FAIL",
  ADD_EMPLOYEE_REQUEST: "ADD_EMPLOYEE_REQUEST",
  ADD_EMPLOYEE_SUCCESS: "ADD_EMPLOYEE_SUCCESS",
  ADD_EMPLOYEE_FAIL: "ADD_EMPLOYEE_FAIL",
  GET_EMPLOYEE_INFO_REQUEST: "GET_EMPLOYEE_INFO_REQUEST",
  GET_EMPLOYEE_INFO_SUCCESS: "GET_EMPLOYEE_INFO_SUCCESS",
  GET_EMPLOYEE_INFO_FAIL: "GET_EMPLOYEE_INFO_FAIL",
  EDIT_EMPLOYEE_INFO_REQUEST: "EDIT_EMPLOYEE_INFO_REQUEST",
  EDIT_EMPLOYEE_INFO_SUCCESS: "EDIT_EMPLOYEE_INFO_SUCCESS",
  EDIT_EMPLOYEE_INFO_FAIL: "EDIT_EMPLOYEE_INFO_FAIL",
};

export default ACTION_TYPES;
