const ACTION_TYPES = {
  GET_ALL_EMPLOYEE_REQUEST: "GET_ALL_EMPLOYEE_REQUEST",
  GET_ALL_EMPLOYEE_SUCCESS: "GET_ALL_EMPLOYEE_SUCCESS",
  GET_ALL_EMPLOYEE_FAIL: "GET_ALL_EMPLOYEE_FAIL",
  ADD_EMPLOYEE_REQUEST: "ADD_EMPLOYEE_REQUEST",
  ADD_EMPLOYEE_SUCCESS: "ADD_EMPLOYEE_SUCCESS",
  ADD_EMPLOYEE_FAIL: "ADD_EMPLOYEE_FAIL",
};

export default ACTION_TYPES;
