const ACTION_TYPES = {
  SAVE_ORDER_REQUEST: "SAVE_ORDER_REQUEST",
  SAVE_ORDER_SUCCESS: "SAVE_ORDER_SUCCESS",
  SAVE_ORDER_FAIL: "SAVE_ORDER_FAIL",
  GET_LIST_ORDER_REQUEST: "GET_LIST_ORDER_REQUEST",
  GET_LIST_ORDER_SUCCESS: "GET_LIST_ORDER_SUCCESS",
  GET_LIST_ORDER_FAIL: "GET_LIST_ORDER_FAIL",
  GET_STATISTIC_REQUEST: "GET_STATISTIC_REQUEST",
  GET_STATISTIC_SUCCESS: "GET_STATISTIC_SUCCESS",
  GET_STATISTIC_FAIL: "GET_STATISTIC_FAIL",
};

export default ACTION_TYPES;
