const ACTION_TYPES = {
  GET_ALL_PRODUCTS_REQUEST: "GET_ALL_PRODUCTS_REQUEST",
  GET_ALL_PRODUCTS_SUCCESS: "GET_ALL_PRODUCTS_SUCCESS",
  GET_ALL_PRODUCTS_FAIL: "GET_ALL_PRODUCTS_FAIL",
  CREATE_PRODUCT_REQUEST: "CREATE_PRODUCT_REQUEST",
  CREATE_PRODUCT_SUCCESS: "CREATE_PRODUCT_SUCCESS",
  CREATE_PRODUCT_FAIL: "CREATE_PRODUCTS_FAIL",
  UPDATE_PRODUCT_INFO_REQUEST: "UPDATE_PRODUCT_INFO_REQUEST",
  UPDATE_PRODUCT_INFO_SUCCESS: "UPDATE_PRODUCT_INFO_SUCCESS",
  UPDATE_PRODUCT_INFO_FAIL: "UPDATE_PRODUCT_INFO_FAIL",
  GET_PRODUCTS_DISPLAY_REQUEST: "GET_PRODUCTS_DISPLAY_REQUEST",
  GET_PRODUCTS_DISPLAY_SUCCESS: "GET_PRODUCTS_DISPLAY_SUCCESS",
  GET_PRODUCTS_DISPLAY_FAIL: "GET_PRODUCTS_DISPLAY_FAIL",
  GET_PRODUCT_DETAIL_REQUEST: "GET_PRODUCT_DETAIL_REQUEST",
  GET_PRODUCT_DETAIL_SUCCESS: "GET_PRODUCT_DETAIL_SUCCESS",
  GET_PRODUCT_DETAIL_FAIL: "GET_PRODUCTS_DISPLAY_FAIL",
};

export default ACTION_TYPES;
