const ACTION_TYPES = {
  UPDATE_RATING_REQUEST: "UPDATE_RATING_REQUEST",
  UPDATE_RATING_SUCCESS: "UPDATE_RATING_SUCCESS",
  UPDATE_RATING_FAIL: "UPDATE_RATING_FAIL",
  GET_PREDICT_REQUEST: "GET_PREDICT_REQUEST",
  GET_PREDICT_SUCCESS: "GET_PREDICT_SUCCESS",
  GET_PREDICT_FAIL: "GET_PREDICT_FAIL",
};

export default ACTION_TYPES;
