const ACTION_TYPES = {
  GET_ALL_SUPPLIER_REQUEST: "GET_ALL_SUPPLIER_REQUEST",
  GET_ALL_SUPPLIER_SUCCESS: "GET_ALL_SUPPLIER_SUCCESS",
  GET_ALL_SUPPLIER_FAIL: "GET_ALL_SUPPLIER_FAIL",
  GET_INFO_SUPPLIER_REQUEST: "GET_INFO_SUPPLIER_REQUEST",
  GET_INFO_SUPPLIER_SUCCESS: "GET_INFO_SUPPLIER_SUCCESS",
  GET_INFO_SUPPLIER_FAIL: "GET_INFO_SUPPLIER_FAIL",
  EDIT_INFO_SUPPLIER_REQUEST: "EDIT_INFO_SUPPLIER_REQUEST",
  EDIT_INFO_SUPPLIER_SUCCESS: "EDIT_INFO_SUPPLIER_SUCCESS",
  EDIT_INFO_SUPPLIER_FAIL: "EDIT_INFO_SUPPLIER_FAIL",
  ADD_SUPPLIER_REQUEST: "ADD_SUPPLIER_REQUEST",
  ADD_SUPPLIER_SUCCESS: "ADD_SUPPLIER_SUCCESS",
  ADD_SUPPLIER_FAIL: "ADD_SUPPLIER_FAIL",
  DELETE_SUPPLIER_REQUEST: "DELETE_SUPPLIER_REQUEST",
  DELETE_SUPPLIER_SUCCESS: "DELETE_SUPPLIER_SUCCESS",
  DELETE_SUPPLIER_FAIL: "DELETE_SUPPLIER_FAIL",
  SET_VISIBLE_SUPPLIER_REQUEST: "SET_VISIBLE_SUPPLIER_REQUEST",
  SET_VISIBLE_SUPPLIER_SUCCESS: "SET_VISIBLE_SUPPLIER_SUCCESS",
  SET_VISIBLE_SUPPLIER_FAIL: "SET_VISIBLE_SUPPLIER_FAIL",
};

export default ACTION_TYPES;
